#!/usr/bin/env ruby

require 'optparse'
require_relative 'src/services/meu_carro_novo/search'
require_relative 'src/services/meu_carro_novo/count'
require_relative 'src/models/car'
require_relative 'src/models/config'

def print(cars)
  if $options[:output]
    File.write($options[:output], JSON.pretty_generate(cars))
  else
    p JSON.pretty_generate(cars)
  end
end

Config.load_options

cars = MeuCarroNovo::Search.call($options[:busca].compact)
print(Car.from_json(cars))
p 'Download finalizado.'
p "Resultado salvo em #{$options[:output]}"
